name = "xiaomi-powerbank"
compatibility_date = "2026-07-09"
workers_dev = false

routes = [
  { pattern = "xiaomi-powerbank.leak.moe", custom_domain = true }
]

[assets]
directory = "../dist"
not_found_handling = "single-page-application"
